### ISSUE TITLE
Staxus matching based on first search result, but not right video

### ISSUE THREAD

**Issue by hawkeyefla** [iklier/plex-gay-metadata-agent#15]
So, this one is pretty much Staxus' website and how it returns searches, but not sure how to resolve it.

The video is "Smooth toned body" and the file is named Smooth toned body.mp4 so there should be no issues.  This is the URL for the correct video.  http://staxus.com/trial/gallery.php?id=111

http://staxus.com/trial/search.php?st=advanced&qall=Smooth+toned+body&qany=&qex=&none=&tadded=0  Returns 3 matches where the first two have those terms inside the description, but not the clip name.  The scraper is matching to Foot wank and spunk session!! which as mentioned is the first search result.  http://staxus.com/trial/gallery.php?id=1505

Don't know if it's possible to make it work similar to some of the other scrapers where using the Fix Incorrect Match shows everything that the search found and lets the user pick.

**Comment by MrPlow254** [comment]
I am a bit busy to trouble shoot code for adding new features. Just have enough time to do bugs. I will be free in two weeks.

You can try coding it yourself. Most of the code you are talking about is in helix studio agent. You will have to view the source code of Staxus site to find the correct location of the title, which is also already in the staxus agent. Just reply to here with a pull request. Make a fork of this project and I will verify it works in every situation and accept it or make slight modifications, and use this ["Github desktop"](https://desktop.github.com/)

If you need help understand how to code this make a [state transition diagram](https://en.wikipedia.org/wiki/State_diagram).
