### ISSUE TITLE
AEBN Matching first title in search results, not always the correct title

### ISSUE THREAD

**Issue by hawkeyefla** [iklier/plex-gay-metadata-agent#19]
An example is "British Underwear Party.ext"  When you use AEBN's search it finds the series first and shows them in reverse age order, so #6 comes up first and the agent matches to that.

**Comment by MrPlow254** [comment]
That is already fixed. You need to put the studio name before the title with a - after the studio.

**Comment by MrPlow254** [comment]
Problem fixed.
