### ISSUE TITLE
Sites

### ISSUE THREAD

**Issue by MrPlow254** [iklier/plex-gay-metadata-agent#2]
This can cover a lot of the studios in one go, a few aren't on here.

http://www.aebn.net/

**Comment by phpatnode** [comment]
I think http://www.gayhotmovies.com meets your criteria of "not waybig", "gets updated information across multiple studios/sites", and "has a nice search function and decent size images".  Plus it is focused on gay movies only, unlike aebn which is everything. AND you can choose to retrieve either scenes or entire movies.  It has many popular studios, but a few notable major ones are missing.

http://www.Nakedsword.com is also good and searches for entire movies or scenes as well, but seems to rotate their titles in and out of circulation and a few studios are missing here too.

But if you can make it work, I believe http://www.aebn.net has the largest and most complete database out there.

Hope that helps.

**Comment by MrPlow254** [comment]
AEBN added. No other sites will be added unless proprietary to this agent.
