### ISSUE TITLE
AEBN Matching issue

### ISSUE THREAD

**Issue by hawkeyefla** [iklier/plex-gay-metadata-agent#22]
Working with the title Freaky Chicken at http://gay.theater.aebn.net/dispatcher/movieDetail?genreId=102&theaterId=14077&movieId=164809&locale=en

There appear to be at least two titles with "Freaky Chicken."  I've tried "Vimpex - Freaky Chicken.ext" "Vimpex Freaky Chicken.ext" "Streetdancers - Freaky Chicken.ext" "Streetdancers Freaky Chicken.ext" and it won't match.  Looked in the logs and not really seeing a lot since the AEBN agent seems to not log as much information as Helix or Staxus.

**Comment by MrPlow254** [comment]
I'll look into this latter. Add the studio name in front. e.g. "(staxus) - title name". Also make sure the logs are turned on for AEBN.

**Comment by hawkeyefla** [comment]
Okay, looks like I needed to do the full title of Vimpex Gay Media with () to make this one match.

**Comment by vittsof** [comment]
I tried your Solution with the () in front of the title including the studio name but it still does not match. I try to match (Mustang) - Man Up but with no luck. it matches the first result of Man Up.

Any solution?

**Comment by MrPlow254** [comment]
@vittsof can you provide the log file for debuging

**Comment by vittsof** [comment]
[com.plexapp.agents.aebn.txt](https://github.com/iklier/plex-gay-metadata-agent/files/211908/com.plexapp.agents.aebn.txt)
Thank you for the response.

**Comment by MrPlow254** [comment]
Okay I found the issue and will try and push the fix today. I accidently added a bug into the code that prevented it from working at all. Version 2016.03.10.1 will work correctly.

**Comment by vittsof** [comment]
Thank you Very much!!! I appreciate it!

**Comment by MrPlow254** [comment]
@vittsof I believe the update fixed the issue. Let me know if it continues. I only tested it with one title I had.

**Comment by vittsof** [comment]
@MrPlow254 So far its working just fine. Thank you for your Help!
