### ISSUE TITLE
AEBN Scenes being put into same entry

### ISSUE THREAD

**Issue by hawkeyefla** [iklier/plex-gay-metadata-agent#25]
I was playing around with the AEBN scene support today with a Boy Crush title that I have two scenes from.  The title is "Bus Stop Boys" and I have scenes 3 and 5.  I have them named as Bus Stop Boys Scene 3.mp4 and Bus Stop Boys Scene 5.mp4.

After a scan, I get an entry for Bus Stop Boys Scene 3 and that entry has both files under it. 

Since I don't know if you can add files to to an issue, I've included a PasteBin link with the log entries from the most recent scan.

[Log File](http://pastebin.com/Q5q5i2kC)

**Comment by MrPlow254** [comment]
Well thank you for posting a log file. It looks like it is doing as I coded it is it not? It keeps the scene name and has the unique stars for that scene and genres, and keeps the description and image from the main title.

What specifically are you trying to say? Have just Bus Stop Boys then open that on plex to see options for viewing scenes? I don't know if plex is able to do that. If you can find an agent that does that sort of thing I can add it in.

**Comment by hawkeyefla** [comment]
It retrospect, I believe Plex is performing as designed, and I guess it's not really possible to split what it considers scenes.  So yeah, the agent is as designed here.
