### ISSUE TITLE
Latest Plex update broke "Actors"

### ISSUE THREAD

**Issue by phpatnode** [iklier/plex-gay-metadata-agent#29]
The PLEX update 09.17.2 seems to have broken the ability for the agent to get the actors.  The PLEX release notes included:

(Metadata) Cast/director/writer information is now saved in a new format. (You'll need to refresh content if you downgrade to a previous version of the server.)

I'm assuming that has something to do with that.

**Comment by hawkeyefla** [comment]
Any potential update on this?

**Comment by hawkeyefla** [comment]
Finally found a thread on the Plex support forums talking about the change.  Going to edit my file locally and see what happens.

**Comment by hawkeyefla** [comment]
Okay!  That's it.  role.actor needs to be replaced with role.name

**Comment by ajtatum** [comment]
Hey hawkeyefla -- seems like you get this stuff, have you checked out the other issue... https://github.com/iklier/plex-gay-metadata-agent/issues/31? Maybe you can help out there...?

**Comment by hawkeyefla** [comment]
Eh, I only "get" a little bit of it, and honestly have no clue how Plex and it's agents interact on Windows machines.

**Comment by MrPlow254** [comment]
Okay thanks for your input. I will try and fix the agent soon if gayporncollector.com makes an API. A plex server version check will be needed for backwards compatibility
