### ISSUE TITLE
AEBN titles matching, but not downloading

### ISSUE THREAD

**Issue by hawkeyefla** [iklier/plex-gay-metadata-agent#34]
The Sunshine Twinks from studio YMAC.
The AEBN link is https://gay.theater.aebn.net/dispatcher/movieDetail?genreId=102&theaterId=14077&movieId=92861&locale=en

I have tried it with both (YMAC) and without.  Copied and pasted the title name exactly into the file name.  It just won't download right.

Log snipit.  It seems to find it, but then fails from there.

[aebn.log.txt](https://github.com/iklier/plex-gay-metadata-agent/files/840164/aebn.log.txt)

**Comment by hawkeyefla** [comment]
Okay, this appears to be a bigger AEBN issue.  It seemed to be working fine initially, but now it's not downloading metadata for anything.  Here's another log snippet of 2 
[aebn.log.2.txt](https://github.com/iklier/plex-gay-metadata-agent/files/852111/aebn.log.2.txt)
more titles.

**Comment by hawkeyefla** [comment]
So, tonight the AEBN agent also threw a CRITICAL error scanning something.  More log file goodness attached.



[com.plexapp.agents.aebn.log.txt](https://github.com/iklier/plex-gay-metadata-agent/files/852990/com.plexapp.agents.aebn.log.txt)

**Comment by MrPlow254** [comment]
Will look into this when I get my raspberry pi server working again. I had a fatal crash and have to start from a fresh OS.

**Comment by hawkeyefla** [comment]
Sounds good.  What is interesting is right after you released the latest update, it appeared to work.  I'm going to go back to one of the videos that did work and remove it and readd it to see if there is a trend here.

**Comment by MrPlow254** [comment]
It looks like you are timing out, and that the plugin in working fine. Let me know if this continues. I am adding a new agent soon anyway that is better.

**Comment by hawkeyefla** [comment]
Yeah, it's still happening.  I've gone in and stopped all background downloads, so my connection is free.  But it's random.  Some titles will still load like that title from log 3...I just removed it and added it back, and it downloaded perfectly.  But I also just tried the titles from log 2, and they still won't download.

**Comment by hawkeyefla** [comment]
As a random aside ... I just had 3 titles I added that did not pull anything from AEBN automatically.  I went in and did "Fix Match" and clicked the name in the auto match box, and it was able to pull them.  But the previous titles that won't download, still won't even that way.

**Comment by MrPlow254** [comment]
AEBN has to be put before your local file metadata. You could delete your library and try setting it all up again. None of this seems like problems caused by the plugin.

**Comment by hawkeyefla** [comment]
Created a brand new library as a test.  Same thing.  And local media assets is at the bottom of the list.
[aebn.log.txt](https://github.com/iklier/plex-gay-metadata-agent/files/871108/aebn.log.txt)

**Comment by MrPlow254** [comment]
Okay I'll look into this. I have a new agent I am releasing soon that should be a better more reliable source. I worked with the admin of the site in making the agent.

**Comment by hawkeyefla** [comment]
Is that the site that was being mentioned over on the Plex forums?  I took a look at it.  Lots of potential there.
