### ISSUE TITLE
Unable to access any content from this bundle.  I've uninstalled and reinstalled more than half a dozen times. 

### ISSUE THREAD

**Issue by Gayguy** [iklier/plex-gay-metadata-agent#42]
It does not matter what I do none of the content for these will load in both the web, app.tv can't resolve the issue.

**Comment by MrPlow254** [comment]
@Gayguy can you provide all your steps of what you are doing. I just created a new plex server for myself and had no issue.

**Comment by Gayguy** [comment]
I do not know what is happening with my plex.  There were always issues with playback so the media player is not suitable for the content.  It's quite simple I pick a channel , loads, hangs and message" the channel is not responding."

**Comment by Gayguy** [comment]
I did get a windows update.  Will check back later when I get a chance to see if that might have been the cause.

**Comment by Gayguy** [comment]
Windows Update unfortunately did not help with my problem.
